import React from "react";
import ReactDOM from "react-dom/client";
import CategoryList from "./Components/Home/CategoryList/CategoryList";
import NavBar from "./Components/Home/Navbar/NavBar";
import Home from "./Pages/Home";
import ImageViewer from "./Components/Home/ImageViewer/ImageViewer";
import PageInatationButton from "./Components/Home/PageIantationButton/PageInatationButton";
import { IconBtn } from "./Components/Home/PageIantationButton/iconData";
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<Home />);
